name: Run Tests and Generate Allure Report

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest allure-pytest requests

      - name: Run tests with Allure results
        run: |
          pytest --alluredir=allure-results

      - name: Upload Allure results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Download and generate Allure report
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre-headless
          wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip
          unzip allure-2.21.0.zip -d allure-commandline
          allure-commandline/bin/allure generate allure-results --clean -o allure-report

      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
