name: Run Tests and Generate Allure Report

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest allure-pytest requests

      - name: Run pytest with Allure results
        run: pytest --alluredir=allure-results

      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Download and generate Allure report
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre-headless unzip wget
          wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip
          unzip allure-2.21.0.zip -d allure-commandline
          ./allure-commandline/bin/allure generate allure-results --clean -o allure-report

      - name: Upload Allure HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
